#!/usr/bin/env python3
# Auto-generated by Scientia — GitHub dossier + optional arXiv; set BASE_URL for a REST API.
"""CLI client for skill "softjax"."""
import argparse
import json
import sys

import requests

BASE_URL = ""
REPOSITORY_URL = "https://github.com/a-paulus/softjax"
REFERENCE_URL = "https://arxiv.org/abs/2603.08824"
ARXIV_ID = "2603.08824"
DOCUMENTED_OUTPUT_SHAPE = "array([-0.8792, -0.1641, 0.2767, 0.8738])"


def main() -> None:
    parser = argparse.ArgumentParser(description="Soft differentiable drop-in replacements for non-differentiable JAX functions (abs, relu, sort, argmax, comparison, logical operators, etc.) with adjustable softening strength.")
    parser.add_argument("--mode", type=str, help="Softening mode: 'hard' (non-differentiable), 'soft' (default, smooth approximation), 'smooth', 'c0', 'c1', 'c2' for different continuity guarantees.", default="soft")
    parser.add_argument("--softness", type=str, help="Strength of softening; controls smoothness and boundedness of soft function. Adjustable per operator and method.", default=None)
    parser.add_argument("--method", type=str, help="Algorithm for soft operators like sort: 'softsort', 'neuralsort', 'fast_soft_sort', 'smooth_sort', 'ot', 'sorting_network'.", default="neuralsort")
    parser.add_argument("--k", type=str, help="Number of top elements for top_k operations.", default=None)
    parser.add_argument("--q", type=str, help="Quantile parameter (0\u20131) for quantile and argquantile operations.", default=None)
    parser.add_argument("--descending", type=str, help="Sort order for rank operation: True for descending, False for ascending.", default=True)
    args = parser.parse_args()

    params = {}
    if args.mode is not None:
        params["mode"] = args.mode
    if args.softness is not None:
        params["softness"] = args.softness
    if args.method is not None:
        params["method"] = args.method
    if args.k is not None:
        params["k"] = args.k
    if args.q is not None:
        params["q"] = args.q
    if args.descending is not None:
        params["descending"] = args.descending

    if not str(BASE_URL).strip() and str(REPOSITORY_URL).strip():
        try:
            from scientia.arxiv_util import fetch_arxiv_metadata, suggested_git_clone_command
        except ImportError:
            fetch_arxiv_metadata = None  # type: ignore[assignment]
            suggested_git_clone_command = None  # type: ignore[assignment]

        repo_u = str(REPOSITORY_URL).strip()
        clone_cmd = (
            suggested_git_clone_command(repo_u)
            if suggested_git_clone_command is not None
            else (f"git clone {repo_u}.git" if not repo_u.endswith(".git") else f"git clone {repo_u}")
        )
        out = {
            "status": "ok",
            "skill": "softjax",
            "source_type": "github",
            "execution": "github_repo_dossier",
            "what_this_does": (
                "Parses CLI args and returns JSON: GitHub repository (clone command) plus "
                "optional arXiv paper metadata for explanation."
            ),
            "repository": {
                "url": repo_u,
                "suggested_clone_command": clone_cmd,
                "role": "implementation",
            },
            "params": params,
        }
        ref = str(REFERENCE_URL).strip()
        if ref:
            out["reference_url"] = ref

        if str(ARXIV_ID).strip() and fetch_arxiv_metadata is not None:
            try:
                am = fetch_arxiv_metadata(str(ARXIV_ID).strip())
                out["paper"] = {
                    "role": "arxiv_explanation",
                    "arxiv_abs_url": ref if ref else None,
                    "metadata": am,
                }
            except Exception as exc:  # noqa: BLE001
                out["paper"] = {
                    "role": "arxiv_explanation",
                    "arxiv_error": str(exc),
                    "arxiv_abs_url": ref if ref else None,
                }
        elif ref:
            out["paper"] = {"role": "reference", "url": ref}

        try:
            out["documented_example_shape"] = json.loads(DOCUMENTED_OUTPUT_SHAPE)
        except json.JSONDecodeError:
            out["documented_example_shape_raw"] = DOCUMENTED_OUTPUT_SHAPE
        print(json.dumps(out, indent=2))
        sys.exit(0)

    if not str(BASE_URL).strip():
        out = {
            "status": "stub",
            "skill": "softjax",
            "source_type": "github",
            "execution": "cli_stub_only",
            "what_this_does": (
                "Parses CLI args and returns JSON. Install ``scientia`` for GitHub dossier mode, "
                "or set REPOSITORY_URL / BASE_URL in this script."
            ),
            "message": (
                "Missing repository URL for GitHub dossier mode. "
                "Re-run ``scientia add`` with ``--source-type github`` or edit this script."
            ),
            "params": params,
            "next_steps": [
                "pip install -e <Scientia repo> so ``import scientia.arxiv_util`` works.",
                "Have an HTTP API? Set BASE_URL; adjust method/path/json=/headers.",
            ],
        }
        ref = str(REFERENCE_URL).strip()
        if ref:
            out["reference_url"] = ref
        try:
            out["documented_example_shape"] = json.loads(DOCUMENTED_OUTPUT_SHAPE)
        except json.JSONDecodeError:
            out["documented_example_shape_raw"] = DOCUMENTED_OUTPUT_SHAPE
        print(json.dumps(out, indent=2))
        sys.exit(0)

    try:
        resp = requests.get(BASE_URL, params=params, timeout=30)
        resp.raise_for_status()
        print(json.dumps(resp.json()))
        sys.exit(0)
    except Exception as exc:  # noqa: BLE001
        print(json.dumps({"error": str(exc)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
