#!/usr/bin/env python3
# Auto-generated by Scientia — GitHub dossier + optional arXiv; set BASE_URL for a REST API.
"""CLI client for skill "bioreason_pro"."""
import argparse
import json
import sys

import requests

BASE_URL = ""
REPOSITORY_URL = "https://github.com/bowang-lab/BioReason-Pro"
REFERENCE_URL = "https://www.biorxiv.org/content/10.64898/2026.03.19.712954v1"
ARXIV_ID = ""
DOCUMENTED_OUTPUT_SHAPE = "{}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Multimodal reasoning LLM for protein function prediction integrating protein embeddings with biological context to generate structured reasoning traces and functional annotations.")

    args = parser.parse_args()

    params = {}


    if not str(BASE_URL).strip() and str(REPOSITORY_URL).strip():
        try:
            from scientia.arxiv_util import fetch_arxiv_metadata, suggested_git_clone_command
        except ImportError:
            fetch_arxiv_metadata = None  # type: ignore[assignment]
            suggested_git_clone_command = None  # type: ignore[assignment]

        repo_u = str(REPOSITORY_URL).strip()
        clone_cmd = (
            suggested_git_clone_command(repo_u)
            if suggested_git_clone_command is not None
            else (f"git clone {repo_u}.git" if not repo_u.endswith(".git") else f"git clone {repo_u}")
        )
        out = {
            "status": "ok",
            "skill": "bioreason_pro",
            "source_type": "github",
            "execution": "github_repo_dossier",
            "what_this_does": (
                "Parses CLI args and returns JSON: GitHub repository (clone command) plus "
                "optional arXiv paper metadata for explanation."
            ),
            "repository": {
                "url": repo_u,
                "suggested_clone_command": clone_cmd,
                "role": "implementation",
            },
            "params": params,
        }
        ref = str(REFERENCE_URL).strip()
        if ref:
            out["reference_url"] = ref

        if str(ARXIV_ID).strip() and fetch_arxiv_metadata is not None:
            try:
                am = fetch_arxiv_metadata(str(ARXIV_ID).strip())
                out["paper"] = {
                    "role": "arxiv_explanation",
                    "arxiv_abs_url": ref if ref else None,
                    "metadata": am,
                }
            except Exception as exc:  # noqa: BLE001
                out["paper"] = {
                    "role": "arxiv_explanation",
                    "arxiv_error": str(exc),
                    "arxiv_abs_url": ref if ref else None,
                }
        elif ref:
            out["paper"] = {"role": "reference", "url": ref}

        try:
            out["documented_example_shape"] = json.loads(DOCUMENTED_OUTPUT_SHAPE)
        except json.JSONDecodeError:
            out["documented_example_shape_raw"] = DOCUMENTED_OUTPUT_SHAPE
        print(json.dumps(out, indent=2))
        sys.exit(0)

    if not str(BASE_URL).strip():
        out = {
            "status": "stub",
            "skill": "bioreason_pro",
            "source_type": "github",
            "execution": "cli_stub_only",
            "what_this_does": (
                "Parses CLI args and returns JSON. Install ``scientia`` for GitHub dossier mode, "
                "or set REPOSITORY_URL / BASE_URL in this script."
            ),
            "message": (
                "Missing repository URL for GitHub dossier mode. "
                "Re-run ``scientia add`` with ``--source-type github`` or edit this script."
            ),
            "params": params,
            "next_steps": [
                "pip install -e <Scientia repo> so ``import scientia.arxiv_util`` works.",
                "Have an HTTP API? Set BASE_URL; adjust method/path/json=/headers.",
            ],
        }
        ref = str(REFERENCE_URL).strip()
        if ref:
            out["reference_url"] = ref
        try:
            out["documented_example_shape"] = json.loads(DOCUMENTED_OUTPUT_SHAPE)
        except json.JSONDecodeError:
            out["documented_example_shape_raw"] = DOCUMENTED_OUTPUT_SHAPE
        print(json.dumps(out, indent=2))
        sys.exit(0)

    try:
        resp = requests.get(BASE_URL, params=params, timeout=30)
        resp.raise_for_status()
        print(json.dumps(resp.json()))
        sys.exit(0)
    except Exception as exc:  # noqa: BLE001
        print(json.dumps({"error": str(exc)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
